#!/bin/sh
set -e
if [[ $DOCKER_HOST == unix://* ]]; then
	socket_file=${DOCKER_HOST#unix://}
	if ! [ -S $socket_file ]; then
		cat >&2 <<-EOT
			ERROR: you need to share your Docker host socket with a volume at $socket_file
			Typically you should run your jwilder/nginx-proxy with: \`-v /var/run/docker.sock:$socket_file:ro\`
			See the documentation at http://git.io/vZaGJ
		EOT
        exit 1
	fi
fi
exec /usr/local/bin/docker-gen -watch -only-exposed -notify "nginx -s reload" /etc/docker-gen/nginx.tmpl /etc/nginx/conf.d/default.conf
